#!/usr/bin/env python3
"""portal search brain — shared by index.py (browse) and rank.py (search).

Contains: the message cleaner (recover prose from command-wrapped prompts),
tokenization with compound-splitting (dealflow -> deal flow), a tiny query
expansion map, and tuned BM25. Zero dependencies (numpy/model optional, not required).

Validated config (see scratchpad/PROGRESS.md): compound-split + query-expansion +
title-boost x2. Easy queries ~90%+, robust hit@3 for the live picker UX.
"""
import os
import re

HOME = os.path.expanduser("~")

# ---------------------------------------------------------------- cleaner
_TAG = re.compile(r"<[^>]+>")
# Claude Code prefixes locally-run commands (/resume, /clear, …) with a boilerplate
# caveat. Left in, it becomes the session's "first ask" and poisons both title and arc.
_CAVEAT = re.compile(
    r"caveat:\s*the messages below were generated by the user while running local commands.*?"
    r"(?:unless the user explicitly asks you to\.?|\Z)", re.I | re.S)


def clean_user(t):
    """Recover indexable prose from a raw user message; None if it's pure noise."""
    if not t:
        return None
    t = t.strip()
    t = _CAVEAT.sub(" ", t, count=1).strip()   # drop the local-command boilerplate
    t = _TAG.sub(" ", t)                       # drop <command-*> wrappers, keep prose
    if "## Input" in t:                        # embedded slash-command doc: keep the input
        t = t.split("## Input")[-1]
    # drop slash-command tokens (/loop, /goal) — but not absolute paths: a command is a
    # single /token ending at whitespace, a path continues with another slash
    t = re.sub(r"(?:^|\s)/\w[\w-]*(?=\s|$)", " ", t)
    keep = []
    for ln in t.splitlines():
        s = ln.strip()
        if not s:
            continue
        if s.startswith(("#", "|", "- **", "> ", ">", "1.", "2.", "3.", "```")):
            continue
        low = s.lower()
        if low.startswith(("parse the input", "convert the interval", "examples:",
                            "if the", "otherwise")):
            continue
        keep.append(s)
    t = " ".join(" ".join(keep).split())
    if not t:
        return None
    if t.startswith(("[Image:", "[Request interrupted")) or "Base directory for this skill" in t:
        return None
    if "system-reminder" in t[:40]:
        return None
    return t[:240]


# ---------------------------------------------------------------- tokenization
_WORDS = None


def _wordset():
    global _WORDS
    if _WORDS is None:
        _WORDS = set()
        for p in ("/usr/share/dict/words",):
            try:
                with open(p) as f:
                    for w in f:
                        w = w.strip().lower()
                        if len(w) >= 3:
                            _WORDS.add(w)
                break
            except OSError:
                continue
    return _WORDS


def split_compound(tok):
    """dealflow -> [deal, flow] using the system wordlist; else [tok].

    Only split a token that is NOT itself a real word, into two parts that are
    BOTH >= 4 chars (avoids junk like renders -> rend + ers)."""
    if len(tok) < 8:
        return [tok]
    W = _wordset()
    if not W or tok in W:
        return [tok]
    for i in range(4, len(tok) - 3):
        a, b = tok[:i], tok[i:]
        if a in W and b in W:
            return [a, b]
    return [tok]


def toks(s, compound=True):
    out = []
    for t in re.findall(r"[a-z0-9]+", s.lower()):
        out.extend(split_compound(t) if compound else [t])
    return out


# tiny hand-picked expansion — bridges common paraphrase without a model
EXPAND = {
    "film": ["movie", "cinema", "feature"], "movie": ["film"],
    "financing": ["money", "fund", "finance", "budget"], "finance": ["money", "fund"],
    "docker": ["container", "image"], "container": ["docker"],
    "repo": ["repository", "git"], "picker": ["finder", "selector", "launcher"],
    "install": ["setup", "configure"], "env": ["environment", "secret", "vars"],
    "secret": ["env", "credential", "vault", "key"], "photo": ["image", "picture", "shoot"],
    "dashboard": ["viz", "chart", "analytics"], "graph": ["network", "relationship"],
}


def expand_query(qtoks):
    out = list(qtoks)
    for w in qtoks:
        out.extend(EXPAND.get(w, []))
    return out


# ---------------------------------------------------------------- BM25
class BM25:
    def __init__(self, docs, k1=1.5, b=0.75):
        from collections import Counter
        self.docs = docs
        self.k1, self.b = k1, b
        self.N = len(docs)
        self.tf = [Counter(d) for d in docs]
        self.dl = [len(d) for d in docs]
        self.avgdl = (sum(self.dl) / self.N) if self.N else 0.0
        self.df = Counter()
        for d in docs:
            for w in set(d):
                self.df[w] += 1

    def score(self, i, qtoks):
        import math
        tf, dl = self.tf[i], self.dl[i]
        s = 0.0
        for w in qtoks:
            f = tf.get(w)
            if not f:
                continue
            idf = math.log(1 + (self.N - self.df[w] + 0.5) / (self.df[w] + 0.5))
            s += idf * (f * (self.k1 + 1)) / (f + self.k1 * (1 - self.b + self.b * dl / self.avgdl))
        return s

    def rank(self, qtoks):
        scores = [(self.score(i, qtoks), i) for i in range(self.N)]
        scores.sort(reverse=True)
        return scores  # [(score, idx), ...] high -> low


def doc_tokens(rec, title_boost=2):
    """Build the searchable token list for a session record (title weighted)."""
    title = rec.get("title", "") or ""
    proj = rec.get("project", "") or ""
    search = rec.get("search", "") or ""
    return toks(title) * title_boost + toks(proj) * 2 + toks(search)


# ---------------------------------------------------------------- session type
# ordered: first matching category wins. keyed on whole words in title+search.
_TYPE_RULES = [
    ("comms", ("email", "emails", "reply", "forward", "message", "imessage", "whatsapp",
               "slack", "inbox", "send", "draft", "partnership", "outreach")),
    ("fix",   ("fix", "fixing", "debug", "bug", "broken", "repair", "resolve", "error",
               "issue", "persisting", "saturation", "fidelity")),
    ("data",  ("dashboard", "scrape", "scraper", "dataset", "spreadsheet", "briefing",
               "report", "analytics", "pipeline", "export")),
    ("setup", ("install", "setup", "configure", "config", "provision", "deploy",
               "deployment", "env", "credentials", "keys")),
    ("rsrch", ("research", "investigate", "analyze", "find", "locate", "search", "explore",
               "review", "compare", "identify", "check")),
    ("build", ("build", "create", "make", "website", "site", "app", "prototype", "generate",
               "design", "rebrand", "restage", "iterate", "simulator", "visual", "visuals")),
]
TYPE_GLYPH = {"build": "◆", "fix": "✳", "rsrch": "◎", "comms": "✉",
              "setup": "⚙", "data": "▤", "·": "·"}


def classify_type(title, search, edits=0):
    hay = (" " + " ".join(toks(title) * 2 + toks(search)) + " ")
    scores = {}
    for name, kws in _TYPE_RULES:
        scores[name] = sum(1 for k in kws if (" " + k + " ") in hay)
    best = max(scores, key=lambda n: scores[n]) if any(scores.values()) else None
    if not best:
        return "build" if edits >= 3 else "·"
    return best


# ---------------------------------------------------------------- model label
# raw model id -> short human label. One place, ordered (first substring match wins).
# Includes GPT/Codex ids so the same map serves multi-agent (Claude + Codex) indexing.
_MODEL_MAP = [
    ("opus-4", "Opus 4.x"), ("opus", "Opus"),
    ("sonnet-4", "Sonnet 4.x"), ("sonnet", "Sonnet"),
    ("haiku", "Haiku"),
    ("gpt-5-codex", "Codex GPT-5"), ("codex", "Codex"),
    ("gpt-5", "GPT-5"), ("gpt-4", "GPT-4"),
    ("o4-mini", "o4-mini"), ("o3-mini", "o3-mini"), ("o4", "o4"), ("o3", "o3"),
]


def model_label(raw):
    """Short human label for a raw model id. Unknown/None/synthetic -> 'unknown'."""
    if not raw:
        return "unknown"
    r = str(raw).lower()
    if r.startswith("<") or r == "synthetic":
        return "unknown"
    for key, label in _MODEL_MAP:
        if key in r:
            return label
    return str(raw)[:18]


# ---------------------------------------------------------------- topic terms
_STOP = set("""the a an and or of to in on for with is are be it this that i you we my our your
me us they them he she his her its at by from as into out up down over under again then once
so than too very can will just do does did doing done get got go going want need like make made
use used using look looks looking see seen tell told know now new old add set run open close
please thanks ok okay yes no not all any some more most other into about was were has have had
loop portal claude code session project file files http https www com net org also let s re m t
ll ve don didn isn aren won can t goal masterpiece until keep testing
thoroughly truly works working stuff really actually thing things build built fix fixed
give everything something workflow""".split())

# personal tuning (e.g. your own name so it never becomes a topic chip): one word per
# line in ~/.claude/portal/stopwords.local — kept out of the shipped code.
try:
    with open(os.path.join(HOME, ".claude", "portal", "stopwords.local")) as _f:
        _STOP.update(w.strip().lower() for w in _f if w.strip())
except OSError:
    pass


def topic_terms(tokens, df, ntotal, k=4):
    """Top-k distinctive terms for a session by tf-idf, skipping stopwords/noise.
    Drops any token containing a digit (id fragments like 'bc2c', '1097')."""
    import math
    from collections import Counter
    tf = Counter(t for t in tokens
                 if len(t) >= 3 and t not in _STOP
                 and not any(c.isdigit() for c in t))
    scored = []
    for w, f in tf.items():
        d = df.get(w, 1)
        if d >= max(3, ntotal // 2):     # skip terms common across the corpus
            continue
        idf = math.log(1 + ntotal / d)
        scored.append((f * idf, w))
    scored.sort(reverse=True)
    return [w for _, w in scored[:k]]
